/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class br_edu_ifspsaocarlos_sdm_opencvcamera4_OpencvClass */

using namespace cv;
#ifndef _Included_br_edu_ifspsaocarlos_sdm_opencvcamera4_OpencvClass
#define _Included_br_edu_ifspsaocarlos_sdm_opencvcamera4_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_edu_ifspsaocarlos_sdm_opencvcamera4_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_br_edu_ifspsaocarlos_sdm_opencvcamera4_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
